version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: babycare_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: babycare
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: babycare_redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: .
    image: babycare-app
    container_name: tracking_api
    depends_on:
      - postgres
      - redis
    ports:
      - "8001:8000"
    env_file:
      - .env
    restart: always
    volumes:
      - ./uploads:/app/uploads   # ⭐ image storage folder
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data: